### PR TITLE
#19 create more tests

### PR DESCRIPTION
**Pull request by OuKevin**
Testing 'announceRegistration' and 'announceReset' in Idle.

### CODE REVIEW

**Comment by pavellishin** [comment]
Also, I am beyond stoked that people are contributing to this thing. I know you're getting a t-shirt out of this deal, but this is really helpful.

**Comment by OuKevin** [comment]
Glad to help out! Interested in seeing how this project develops :)

**Comment by OuKevin** [comment]
oops didn't mean to add all those extra commits

**Comment by pavellishin** [comment]
> oops didn't mean to add all those extra commits

No worries, I think I'm probably going to squash-and-merge this.

**Pull request merged**
